<?php echo $this->doctype(); ?>

<html lang="pl">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('Dom Opieki'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <link href='http://fonts.googleapis.com/css?family=Hind&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Gabriela&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/js/jquery-ui/jquery-ui.min.css">
        <link rel="stylesheet" href="/js/CodeMirror/lib/codemirror.css">

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css') ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <script type="text/javascript" src="/js/jquery-ui/jquery-ui.min.js"></script>
        <script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
        <script src="/js/CodeMirror/lib/codemirror.js"></script>
        <script src="/js/CodeMirror/mode/javascript/javascript.js"></script>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Dzienny Dom Pomocy"/></a></div>
                <div class="collapse navbar-collapse">
                    <?php
                    echo $this->navigation('navigation')->menu()->setPartial('partial/mainmenu.phtml'); ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container-fluid">
            <?php echo $this->content; ?>

        </div> <!-- /container -->

    </body>
    <?php echo $this->inlineScript() ?>
</html>
