<?php
$title = $this->translate('News');
$this->headTitle($title);
?>
<div class="row">
<h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php foreach ($news as $singleNews) : ?>
    <div class="col-md-6">
        <img src="<?php echo $this->escapeHtml($singleNews->imgUrl);?>"/>
    </div>
    <div class="col-md-6">
            <h2><?php echo $this->escapeHtml($singleNews->title);?></h2>
        <p><?php
            echo $this->shortDescription($this->escapeHtml($singleNews->description),40);
            ;?>
        </p>
    </div>
        <div class="clearfix"></div>
    <?php endforeach; ?>

</div>