<?php
$title = $this->translate('Aktualności');
$this->headTitle($title);
$colors = ['rgba(34, 143, 206','rgba(21, 12, 70','rgba(172, 31, 103','rgba(225, 29, 39','rgba(49, 132, 80'];
$counter=0;
?>
<div id="news">
<h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php foreach ($news as $singleNews) : ?>
        <div class="row-news">
    <div class="col-md-6 visible-lg visible-md">
        <a class="miniatura" style="background:<?php echo $colors[$counter] ?> ,0.05)" href="/news/single/<?php echo $this->escapeHtml($singleNews->id)?>">
            <?php if ($singleNews->imgList[0]==''):?>
                <img src="http://ddp.mikolow.eu/img/logo.png"/>
            <?php else:?>
                <img src="<?php echo $this->escapeHtml($singleNews->imgList[0]);?>"/>
            <?php endif; ?>
        </a>
    </div>
    <div class="col-md-6">
        <div class="text" style="background:<?php echo $colors[$counter] ?> ,0.1); ">
            <a href="/news/single/<?php echo $this->escapeHtml($singleNews->id)?>">
                <h2 style="color:<?php echo $colors[$counter] ?>,1)"><?php echo $this->escapeHtml($singleNews->title);?></h2></a>
            <p>
                <?php
                echo $this->shortDescription($singleNews->description,160);
                ;?>
            </p>
            <a style="color:<?php echo $colors[$counter] ?>,1)" href="/news/single/<?php echo $this->escapeHtml($singleNews->id)?>">
                WIĘCEJ <i class="fa fa-angle-double-right" aria-hidden="true"></i>
            </a>
        </div>
    </div>
<div class="clearfix"></div>
        </div>
        <?php if ($counter == sizeof($colors) - 1)
        {$counter=0;}
        else {$counter++;} ?>
    <?php endforeach; ?>
</div>
