<?php
$title = $this->translate('Aktualność');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($news->title);?></h1>
<div class="row">
    <div class="col-md-6">
        <img src="<?php echo $this->escapeHtml($news->imgList[0]);?>"/>
    </div>
    <?php
    $length = count($news->imgList);
    if ($length>1) :?>
        <div class="col-md-6">
        <div class="row">
        <?php for ($x = 1; $x < $length; $x++) : ?>

                    <div class="col-sm-6">
                        <img src="<?php echo $this->escapeHtml($news->imgList[$x]);?>"/>
                    </div>

        <?php endfor; ?>
        </div>
        </div>
            <div class="col-md-12">
                <p><?php echo $news->description;?></p>
            </div>

    <?php else: ?>
        <div class="col-md-6">
            <p><?php echo $news->description;?></p>
        </div>
    <?php endif; ?>

</div>