<?php
$title = $this->translate('Aktualność');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($news->title);?></h1>
<div class="row">
    <div class="col-md-6">
        <img src="<?php echo $this->escapeHtml($news->imageList[0]);?>"/>
    </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-sm-6">

                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <p><?php echo $news->description;?></p>
            </div>

</div>