<?php
    $title = $this->translate('Edycja Podstron');
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('adminSubsites', array('action'=>'add'));?>">Dodaj subsitesa</a>
</p>

<table class="table">
    <tr>
        <th>Tytul</th>
        <th>Opis</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($subsites as $singleSubsites) : ?>
        <tr>
            <td><a href="/info/<?php echo $this->escapeHtml($singleSubsites->url); ?>"><?php echo $this->escapeHtml($singleSubsites->title);?></a></td>
            <td><?php echo $this->shortDescription($singleSubsites->description,200);?></td>
            <td>
                <a href="/info/<?php echo $this->escapeHtml($singleSubsites->url);?>">Przeglądaj</a>
                <a href="<?php echo $this->url('adminSubsites',
                    array('action'=>'edit', 'id' => $singleSubsites->id));?>">Edycja</a>
                <a href="<?php echo $this->url('adminSubsites',
                    array('action'=>'delete', 'id' => $singleSubsites->id));?>">Usu&#324;</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>