<?php
    $title = $this->translate('Edycja Podstron');
    $this->headTitle($title);
$filter
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="col-md-2">

    <ul>
        <li><a href="/admin/news">Aktualności</a></li>
        <li><a href="/admin/subsites">Podstrony</a></li>
        <li><a href="/admin/media">Media</a></li>
        <li><a href="/login/logout">Wyloguj</a></li>
    </ul>
</div>
<div class="col-md-10">
<p>
    <a href="<?php echo $this->url('adminSubsites', array('action'=>'add'));?>">Dodaj nową podstronę</a>
</p>

<table class="table">
    <tr>
        <th>Tytul</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($subsites as $singleSubsites) : ?>
        <tr>
            <td><a href="/info/<?php echo $this->escapeHtml($singleSubsites->url); ?>"><?php echo $this->escapeHtml($singleSubsites->title);?></a></td>


                <td><a href="/info/<?php echo $this->escapeHtml($singleSubsites->url);?>">Przeglądaj</a></td>
            <td><a href="<?php echo $this->url('adminSubsites',
                    array('action'=>'edit', 'id' => $singleSubsites->id));?>">Edycja</a></td>
            <td><a href="<?php echo $this->url('adminSubsites',
                    array('action'=>'delete', 'id' => $singleSubsites->id));?>">Usu&#324;</a></td>

        </tr>
    <?php endforeach; ?>
</table>
    </div>