<?php
    $title = $this->translate('Subsites');
    $this->headTitle($title);
    $filter = new Zend\Filter\StripTags();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('adminSubsites', array('action'=>'add'));?>">Dodaj subsitesa</a>
</p>

<table class="table">
    <tr>
        <th>Tytul</th>
        <th>Opis</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($subsites as $singleSubsites) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($singleSubsites->title);?></td>
            <td><?php echo $filter->filter($singleSubsites->description)?></td>
            <td>
                <a href="<?php echo $this->url('adminSubsites',
                    array('action'=>'edit', 'id' => $singleSubsites->id));?>">Edycja</a>
                <a href="<?php echo $this->url('adminSubsites',
                    array('action'=>'delete', 'id' => $singleSubsites->id));?>">Usuń</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>