<?php
    $title = $this->translate('News');
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('adminNews', array('action'=>'add'));?>">Dodaj newsa</a>
</p>

<table class="table">
    <tr>
        <th>Tytul</th>
        <th>Opis</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($news as $singleNews) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($singleNews->title);?></td>
            <td><?php echo $this->escapeHtml($singleNews->description);?></td>
            <td>
                <a href="<?php echo $this->url('adminNews',
                    array('action'=>'edit', 'id' => $singleNews->id));?>">Edit</a>
                <a href="<?php echo $this->url('adminNews',
                    array('action'=>'delete', 'id' => $singleNews->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>