<?php
    $title = $this->translate('Aktualność');
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

    <div class="col-md-2">

        <ul>
            <li><a href="/admin/news">Aktualności</a></li>
            <li><a href="/admin/subsites">Podstrony</a></li>
            <li><a href="/admin/media">Media</a></li>
            <li><a href="/login/logout">Wyloguj</a></li>
        </ul>
    </div>
    <div class="col-md-10">
<p>
    <a href="<?php echo $this->url('adminNews', array('action'=>'add'));?>">Dodaj aktualność</a>
</p>

<table class="table">
    <tr>
        <th>Tytuł</th>
        <th>Opis</th>
        <th>Miniaturka</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($news as $singleNews) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($singleNews->title);?></td>
            <td><?php echo $this->shortDescription($this->escapeHtml($singleNews->description),40);?></td>
            <td><img style="max-width:100px;" src="<?php echo $this->escapeHtml($singleNews->imgList[0]);?>"/></td>
            <td>
                <a href="<?php echo $this->url('adminNews',
                    array('action'=>'edit', 'id' => $singleNews->id));?>">Edycja</a>
                <a href="<?php echo $this->url('adminNews',
                    array('action'=>'delete', 'id' => $singleNews->id));?>">Usuń</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
        </div>
