<div id="carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel" data-slide-to="0" class="active"></li>
        <li data-target="#carousel" data-slide-to="1"></li>
        <li data-target="#carousel" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="slider">
                    <div class="col-md-6">
                        <img src="/img/logo.png" class="img-responsive first"/>
                    </div>
                    <div class="col-md-6">
                        <div class=" second">
                            <h2>Witamy na stronie</h2>
                            <p>
                                Dziennego Domu Pomocy w Mikołowie
                            </p>
                        </div>
                    </div>

            </div>
        </div>
        <div class="item">
            <div class="slider">
                <div class="col-md-6">
                    <div class="first-invert">
                        <h2>Potrzebujesz pomocy ?</h2>
                        <p>
                            Zadzwoń: <b>32 226 00 90</b><br/>
                            Pon - Pia 7.30 do 15.30
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <i class="fa fa-phone-square second-invert" aria-hidden="true"></i>
                 </div>
            </div>
        </div>
        <div class="item">
            <div class="slider">
                <div class="col-md-6">
                    <div class="first">
                        <h2>Pomoc i opiekę</h2>
                        <p>
                            zapewniamy w godnych warunkach i przyjaznej atmosferze.
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <i class="fa fa-smile-o" aria-hidden="true"> </i>
                </div>
            </div>
        </div>
       

    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">

    </a>
    <a class="right carousel-control" href="#carousel" role="button" data-slide="next">

    </a>

</div>
<script type="text/javascript">

    $('#carousel').carousel({
        pause: "false"
    });

</script>