<?php
$escaper = new Zend\Escaper\Escaper('utf-8');
?>
<div id="carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel" data-slide-to="0" class="active"></li>
        <li data-target="#carousel" data-slide-to="1"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="item-image" style="background-image: url('http://ddp.mikolow.eu/upload/slider7.jpg')">
            <div class="carousel-caption">
                <h2>Przyjazne miejsce</h2>
                <p>
                    dla ludzi w starszym wieku, pragnących godnie spędzić czas.
                </p>
            </div>
            </div>
        </div>
        <div class="item">
            <div class="item-image" style="background-image: url('http://ddp.mikolow.eu/upload/slider6.jpg')">
                <div class="carousel-caption">

                </div>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">

    </a>
    <a class="right carousel-control" href="#carousel" role="button" data-slide="next">

    </a>

</div>


<div class="col-md-8">
    <div class="box">
        <div id="quick-news">
            <div class="row">
                <h2 class="title">Aktualności</h2>
                <div class="box-content">
                <?php $index=0;
                foreach ($news as $singleNews) : ?>

                    <div class="col-md-3 visible-lg visible-md">
                        <a href="/news/single/<?php echo $this->escapeHtml($singleNews->id) ?>">
                            <?php if ($singleNews->imgList[0] == ''): ?>
                                <img class="img-responsive thumbnail" src="http://ddp.mikolow.eu/img/logo.png"/>
                            <?php else: ?>
                                <img class="img-responsive thumbnail"
                                     src="<?php echo $this->escapeHtml($singleNews->imgList[0]); ?>"/>
                            <?php endif; ?>
                        </a>
                    </div>
                    <div class="col-md-9">
                        <div class="text">
                            <a href="/news/single/<?php echo $this->escapeHtml($singleNews->id) ?>">
                                <h2><?php echo $this->escapeHtml($singleNews->title); ?></h2></a>
                            <p>
                                <?php
                                echo $this->shortDescription($singleNews->description, 320);; ?>
                            </p>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <?php
                    if($index==1){break;}
                    $index++;
                    ?>



            <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="box">
        <div id="quick-contact">
            <?php
            foreach ($subsites as $singleSubsites) : ?>
                <?php if ($singleSubsites->title == "Kontakt") : ?>
                    <h2 class="title"><?php echo $this->escapeHtml($singleSubsites->title); ?></h2>
                    <div class="box-content"> <?php echo $this->quickContact($singleSubsites->description); ?></div>
                <?php endif ?>


            <?php endforeach; ?>
            <center><a href="http://bip.mikolow.eu/index.php/documents/document/74"><img style="border:0;" src="https://www.bip.gov.pl/img/logo_glowne.jpg"></a></center>
        </div>
    </div>
</div>


<script type="text/javascript">

    $('#carousel').carousel({
        pause: "false"
    });

</script>